# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import person.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('0', '有效'), ('1', '失效')], default=0, max_length=10, verbose_name='State')),
                ('issue_date', models.DateField(verbose_name='发证时间')),
                ('reg_date', models.DateField(blank=True, null=True, verbose_name='登记时间')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期')),
            ],
            options={
                'verbose_name': '证件',
                'verbose_name_plural': '证件',
            },
        ),
        migrations.CreateModel(
            name='CertificatePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('0', '有效'), ('1', '失效')], default=0, max_length=10, verbose_name='State')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片说明')),
                ('photo', models.ImageField(upload_to=person.models.CertificatePhoto.certificate_file_name, verbose_name='图片')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CertificatePhoto', to='person.Certificate', verbose_name='证件名称')),
            ],
            options={
                'verbose_name': '证件图片',
                'verbose_name_plural': '证件图片',
            },
        ),
        migrations.CreateModel(
            name='CertificateRecod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('0', '有效'), ('1', '失效')], default=0, max_length=10, verbose_name='State')),
                ('borrow_people', models.CharField(max_length=80, verbose_name='借用人')),
                ('borrow_date', models.DateField(verbose_name='借用时间')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='归还时间')),
                ('use', models.TextField(blank=True, verbose_name='备注')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CertificateRecod', to='person.Certificate', verbose_name='证件名称')),
                ('use_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Project', verbose_name='使用单位')),
            ],
            options={
                'verbose_name': '证件使用记录',
                'verbose_name_plural': '证件使用记录',
            },
        ),
        migrations.CreateModel(
            name='CertificatesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='证件类别')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='类型')),
                ('issue', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '证件类别',
                'verbose_name_plural': '证件类别',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('0', '有效'), ('1', '失效')], default=0, max_length=10, verbose_name='State')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='地址')),
                ('mobile', models.CharField(blank=True, max_length=12, verbose_name='手机')),
                ('telephone', models.CharField(blank=True, max_length=8, verbose_name='固定电话')),
                ('email', models.EmailField(blank=True, max_length=75, verbose_name='邮箱')),
                ('qq', models.CharField(blank=True, max_length=12, verbose_name='QQ')),
            ],
            options={
                'verbose_name': '联系方式',
                'verbose_name_plural': '联系方式',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('0', '有效'), ('1', '失效')], default=0, max_length=10, verbose_name='State')),
                ('name', models.CharField(max_length=250, verbose_name='姓名')),
                ('identification', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('gender', models.CharField(choices=[('Male', '男'), ('Female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('avatar', models.ImageField(blank=True, upload_to=person.models.Person.avatar_file_name, verbose_name='证件照')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_year', models.CharField(max_length=10, verbose_name='归集年度')),
                ('pay_year', models.CharField(max_length=10, verbose_name='发放年度')),
                ('pay_month', models.CharField(choices=[('1', '1月'), ('2', '2月'), ('3', '3月'), ('4', '4月'), ('5', '5月'), ('6', '6月'), ('7', '7月'), ('8', '8月'), ('9', '9月'), ('10', '10月'), ('11', '11月'), ('12', '12月')], max_length=10, verbose_name='发放月份')),
                ('pay_type', models.CharField(choices=[('1', '月度工资'), ('2', '奖励'), ('3', '预兑现'), ('4', '兑现余额'), ('5', '补贴')], default='1', max_length=10, verbose_name='类别')),
                ('pay_money', models.CharField(max_length=10, verbose_name='金额')),
                ('pay_use', models.TextField(blank=True, verbose_name='备注')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='姓名')),
            ],
            options={
                'verbose_name': '薪资发放',
                'verbose_name_plural': '薪资发放',
            },
        ),
        migrations.CreateModel(
            name='Workrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('0', '有效'), ('1', '失效')], default=0, max_length=10, verbose_name='State')),
                ('job_start_date', models.DateField(verbose_name='开始时间')),
                ('job_end_date', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Post', verbose_name='岗位')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Company', verbose_name='公司')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Department', verbose_name='部门')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='姓名')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Project', verbose_name='项目部')),
            ],
            options={
                'verbose_name': '工作经历',
                'verbose_name_plural': '工作经历',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificates_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.CertificatesType', verbose_name='证件名称'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='姓名'),
        ),
    ]
