# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='belong_year',
            field=models.CharField(choices=[('2014', '2014年'), ('2015', '2015年'), ('2016', '2016年'), ('2017', '2017年'), ('2018', '2018年')], max_length=10, verbose_name='归集年度'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='pay_type',
            field=models.CharField(choices=[('1', '月度工资'), ('2', '奖励'), ('3', '预兑现'), ('4', '兑现余额'), ('5', '资质补贴'), ('6', '其他')], default='1', max_length=10, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='pay_year',
            field=models.CharField(choices=[('2014', '2014年'), ('2015', '2015年'), ('2016', '2016年'), ('2017', '2017年'), ('2018', '2018年')], max_length=10, verbose_name='发放年度'),
        ),
    ]
