# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20170811_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='person',
        ),
        migrations.AddField(
            model_name='salary',
            name='persons',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='championed_by', to='person.Person', verbose_name='姓名'),
            preserve_default=False,
        ),
    ]
