# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20170815_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='pay_money',
            field=models.IntegerField(max_length=10, verbose_name='金额'),
        ),
    ]
