# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20170818_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='pay_money',
            field=models.IntegerField(verbose_name='金额'),
        ),
    ]
