# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20170818_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='pay_money',
            field=models.FloatField(verbose_name='金额'),
        ),
    ]
