# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20170818_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='persons',
        ),
        migrations.AddField(
            model_name='salary',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='姓名'),
            preserve_default=False,
        ),
    ]
