# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_auto_20170820_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telephone_short',
            field=models.CharField(blank=True, max_length=5, verbose_name='固定电话'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='qq',
            field=models.CharField(blank=True, max_length=13, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, verbose_name='固定电话'),
        ),
    ]
