# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_auto_20170820_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='state',
            field=models.CharField(choices=[('0', '有效'), ('1', '失效')], default=0, max_length=10, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='salary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone_short',
            field=models.CharField(blank=True, max_length=5, verbose_name='小号'),
        ),
    ]
