# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '__first__'),
        ('person', '0012_auto_20170904_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('0', '有效'), ('1', '失效')], default=0, max_length=10, verbose_name='State')),
                ('type', models.CharField(choices=[('0', '有期限'), ('1', '无固定期限')], default='1', max_length=10, verbose_name='合同类型')),
                ('Contract_start_date', models.DateField(verbose_name='开始时间')),
                ('Contract_end_date', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Company', verbose_name='甲方')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='姓名')),
            ],
            options={
                'verbose_name': '劳动合同',
                'verbose_name_plural': '劳动合同',
            },
        ),
    ]
